"""Regression coverage for durable provenance on URL-backed Stash files."""

from __future__ import annotations

import io
import json
from unittest.mock import patch

from PIL import Image
import pytest

from lib import stash_helper


def test_save_from_url_persists_requested_and_final_urls(tmp_path):
    space = stash_helper.StashSpace("space_test", tmp_path)
    space.create()
    requested_url = "https://images.example/reference.jpg?label=%3Cuntrusted%3E"
    final_url = "https://cdn.example/reference.jpg"

    with patch.object(
        stash_helper,
        "safe_download",
        return_value=(b"image bytes", "image/jpeg", final_url),
    ):
        saved = stash_helper.StashFile(space).save_from_url(
            requested_url,
            name="reference.jpg",
            tool_origin="stash",
        )

    persisted = json.loads((space.space_path / "meta.json").read_text())
    file_meta = next(
        item for item in persisted["files"] if item["file_id"] == saved["file_id"]
    )

    assert saved["source_url"] == requested_url
    assert saved["final_url"] == final_url
    assert file_meta["source_url"] == requested_url
    assert file_meta["final_url"] == final_url
    assert (space.space_path / "reference.jpg").read_bytes() == b"image bytes"


def test_non_url_stash_files_do_not_gain_url_provenance(tmp_path):
    space = stash_helper.StashSpace("space_test", tmp_path)
    space.create()

    saved = stash_helper.StashFile(space).save_binary(
        b"generated bytes",
        "generated.jpg",
        mime_type="image/jpeg",
        tool_origin="generate_image",
    )

    persisted = json.loads((space.space_path / "meta.json").read_text())
    file_meta = next(
        item for item in persisted["files"] if item["file_id"] == saved["file_id"]
    )

    assert "source_url" not in file_meta
    assert "final_url" not in file_meta


def _png_bytes(width: int = 1800, height: int = 900) -> bytes:
    output = io.BytesIO()
    Image.new("RGB", (width, height), (25, 75, 125)).save(output, format="PNG")
    return output.getvalue()


def test_safe_download_image_decodes_and_bounds_real_raster_bytes():
    with patch.object(
        stash_helper,
        "safe_download",
        return_value=(
            _png_bytes(),
            "application/octet-stream",
            "https://cdn.example/reference.png",
        ),
    ):
        data, mime_type, final_url, metadata = stash_helper.safe_download_image(
            "https://images.example/reference"
        )

    with Image.open(io.BytesIO(data)) as image:
        assert image.format == "JPEG"
        assert image.size == (1024, 512)
    assert mime_type == "image/jpeg"
    assert final_url == "https://cdn.example/reference.png"
    assert metadata["detected_format"] == "png"
    assert metadata["original_width"] == 1800
    assert metadata["processed_width"] == 1024
    assert metadata["resized_for_safety"] is True


def test_safe_download_image_rejects_html_even_with_image_header():
    with patch.object(
        stash_helper,
        "safe_download",
        return_value=(
            b"<html><script>alert('not an image')</script></html>",
            "image/jpeg",
            "https://malicious.example/payload.jpg",
        ),
    ), pytest.raises(stash_helper.SecurityError, match="valid JPEG"):
        stash_helper.safe_download_image("https://images.example/redirect")


def test_save_image_from_url_persists_only_processed_raster(tmp_path):
    space = stash_helper.StashSpace("space_test", tmp_path)
    space.create()
    requested_url = "https://images.example/reference.png"
    final_url = "https://cdn.example/reference.png"

    with patch.object(
        stash_helper,
        "safe_download",
        return_value=(_png_bytes(), "image/png", final_url),
    ):
        saved = stash_helper.StashFile(space).save_image_from_url(
            requested_url,
            name="reference.png",
            tool_origin="serpapi_google_images_light",
        )

    persisted = json.loads((space.space_path / "meta.json").read_text())
    file_meta = next(
        item for item in persisted["files"] if item["file_id"] == saved["file_id"]
    )

    assert saved["name"] == "reference.jpg"
    assert saved["mime_type"] == "image/jpeg"
    assert file_meta["source_url"] == requested_url
    assert file_meta["final_url"] == final_url
    assert file_meta["processed_width"] == 1024
    with Image.open(space.space_path / saved["stored_name"]) as image:
        assert image.format == "JPEG"
