#!/usr/bin/env python3
"""
Tool Builder - Autonomous tool creation from feedback gaps.

Uses existing LLM providers to generate new tools when consistent gaps
are identified in feedback. Includes safety checks, verification, and
full traceability.

Usage:
    from tool_builder import ToolBuilder
    builder = ToolBuilder(mode='cloud')
    result = builder.build_tool(gap_description, feedback_ids)
"""

import os
import sys
import json
import ast
import subprocess
import re
from datetime import datetime
from pathlib import Path
from dataclasses import dataclass, asdict

# Add lib to path
sys.path.insert(0, os.path.dirname(__file__))
from config_loader import load_config, get_config_value
from llm_provider import create_provider

# Directories
SKILLS_DIR = Path(__file__).parent.parent / "skills"
AUTO_TOOLS_DIR = SKILLS_DIR / "auto-tools"
PENDING_DIR = SKILLS_DIR / "pending"
LOGS_DIR = Path(__file__).parent.parent / "logs" / "tool-builder"

# Ensure directories exist
AUTO_TOOLS_DIR.mkdir(exist_ok=True)
PENDING_DIR.mkdir(exist_ok=True)
LOGS_DIR.mkdir(parents=True, exist_ok=True)

# Packages already available (no pip install needed)
AVAILABLE_PACKAGES = {
    # Standard library
    "os", "sys", "json", "re", "datetime", "time", "subprocess",
    "pathlib", "typing", "dataclasses", "collections", "itertools",
    "functools", "math", "statistics", "random", "hashlib", "base64",
    "urllib", "http", "socket", "sqlite3", "csv", "io", "tempfile",
    "shutil", "glob", "argparse", "logging", "traceback", "copy",
    
    # Jarvis lib modules (auto-available via sys.path.insert)
    "config_loader", "stash_helper", "memory_db", "llm_provider", "http_client",
    
    # Already installed in jarvis-venv
    "requests", "anthropic", "openai", "httpx", "pydantic",
    "fastapi", "uvicorn", "yt-dlp", "yfinance", "xai_sdk",
    
    # Data Science & Math
    "numpy", "scipy", "sympy", "mpmath",
    "scikit-learn", "sklearn", "joblib", "threadpoolctl",
    
    # Web & Parsing
    "flask", "flask_cors", "bs4", "beautifulsoup4", "lxml",
    
    # Config & Data Formats
    "yaml", "pyyaml", "dotenv", "toml",
    
    # Date/Time
    "python_dateutil", "dateutil", "pytz",
    
    # System & Process
    "psutil", "packaging", "setuptools",
    
    # Audio/Video
    "av", "sounddevice", "soundfile", "speexdsp",
    
    # ML/AI
    "ctranslate2", "faster-whisper", "openwakeword",
    "huggingface-hub", "tokenizers", "onnxruntime",
    
    # File & I/O
    "filelock", "fsspec", "certifi", "charset-normalizer",
    "idna", "urllib3", "tqdm", "pymupdf", "fpdf2",
    
    # Monitoring
    "prometheus-fastapi-instrumentator", "coloredlogs", "humanfriendly",
    
    # Protocol & Encoding
    "protobuf", "flatbuffers", "cffi", "pycparser",
    
    # UI
    "textual",
    
    # Misc
    "typing_extensions", "hf-xet",
}


@dataclass
class ToolBuildResult:
    """Result of a tool build attempt."""
    success: bool
    tool_name: str | None = None
    tool_path: str | None = None
    status: str = "unknown"  # created, pending_review, failed
    message: str = ""
    report_card: dict | None = None
    retries_used: int = 0
    needs_packages: list[str] = None
    
    def __post_init__(self):
        if self.needs_packages is None:
            self.needs_packages = []


@dataclass
class ToolReportCard:
    """Audit trail for why a tool was created."""
    tool_name: str
    created_at: str
    created_by: str  # "auto_builder" or "manual"
    mode: str  # cloud/local
    
    # Why it was created
    gap_description: str
    purpose: str
    feedback_ids: list[str]
    evolution_ids: list[str]
    
    # What it does
    capabilities: list[str]
    parameters: dict[str, str]
    
    # Verification
    verification_passed: bool
    verification_output: str
    test_input_used: dict
    test_output: str
    
    # Dependencies
    packages_required: list[str]
    packages_new: list[str]  # Packages that needed install
    
    # MCP check
    mcp_alternatives_checked: list[str]
    mcp_overlap_reason: str  # Why we built instead of using MCP
    
    # LLM details
    builder_provider: str
    builder_model: str
    generation_retries: int
    
    # API Key requirements (optional - have defaults so must be last)
    requires_api_key: bool = False
    suggested_env_var: str | None = None


TOOL_TEMPLATE = '''#!/usr/bin/env python3
"""
{description}

Auto-generated by Jarvis Tool Builder
Created: {created_at}
Feedback IDs: {feedback_ids}

Input: {input_schema}
Output: {{ "ok": bool, "speech": str, "data": dict }}
"""

import sys
import os
import json

# Add lib to path (tool lives in skills/auto-tools/, so go up 2 levels)
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'lib'))
from config_loader import load_config, get_config_value

{imports}

def main():
    try:
        # Parse arguments
        if len(sys.argv) > 1:
            args = json.loads(sys.argv[1])
        else:
            args = json.load(sys.stdin)
        
        # Load config
        load_config()
        
{main_logic}
        
    except Exception as e:
        print(json.dumps({{
            "ok": False,
            "error": str(e),
            "speech": f"Error: {{e}}"
        }}))
        sys.exit(1)


if __name__ == "__main__":
    main()
'''


TOOL_JSON_TEMPLATE = '''{
  "enabled": true,
  "name": "{name}",
  "description": "{description}",
  "script": "{script}",
  "parameters": {parameters},
  "permissions": {permissions},
  "test_input": {test_input},
  "expected_output_contains": {expected_output},
  "auto_generated": true,
  "created_at": "{created_at}",
  "feedback_ids": {feedback_ids}
}
'''


BUILD_PROMPT = '''You are a tool builder for a voice assistant named Jarvis.

A capability gap has been identified:
{gap_description}

Related feedback that identified this gap:
{feedback_context}

EXISTING TOOLS - DO NOT DUPLICATE THESE:
{existing_tools}

Note: If an existing tool already does what's requested (even partially), respond with SKIP_DUPLICATE.

SYSTEM INFO:
- Python version: {python_version}
- Available env vars with API keys: {available_api_keys}

YOUR TASK: Create a Python tool to fill this gap.

REQUIREMENTS:
1. Tool MUST be a single Python file
2. MUST follow the exact template structure (see below)
3. MUST return JSON: {{"ok": true/false, "speech": "...", "data": {{...}}}}
4. Keep it SIMPLE - single purpose, minimal dependencies
5. If an MCP tool already does this, respond with SKIP_MCP_EXISTS
6. If this is trivial/unnecessary, respond with SKIP_TRIVIAL

API KEY RULES:
- ONLY use API keys that are listed in "Available env vars" above
- If the tool REQUIRES an API key that doesn't exist, set "requires_new_api_key": true
- Specify which env var name should be added (e.g., "suggested_env_var": "SOME_API_KEY")
- Tools requiring new API keys will be queued for manual setup
- You are NOT required to use an API key, but if you do follow the rules above.

AVAILABLE PACKAGES (no install needed):
{available_packages}

If you need OTHER packages, list them but the tool may be queued for review.

RESEARCH AVAILABLE:
If you need current information about an API or library, research has been provided below.
{research_context}

STASH SYSTEM - USE FOR MULTI-STEP WORKFLOWS:
When your tool downloads files, creates content, or produces artifacts that other tools might need:

WHEN TO USE STASH:
- Downloading files/images from URLs for later use (PDF creation, email attachment, printing)
- Storing generated content (transcripts, converted files, reports)
- Caching intermediate data between tool calls
- Any output the user might want to print, email, or process further

WHEN NOT TO USE STASH:
- Simple text responses (just return in speech/data)
- Permanent facts/preferences (use memory_db.remember() instead)
- One-time computations without file output

HOW TO USE STASH (import from lib/stash_helper.py, NOT subprocess):
```python
# Import at top of file (after sys.path.insert)
from stash_helper import open_space, StashFile

# Create/reuse a stash space with descriptive labels
space, is_new = open_space(scope='session', labels=['youtube_transcripts'])

# Save text content
stash_file = StashFile(space)
result = stash_file.save_text(
    content="text content here",
    name="filename.txt",
    on_conflict='overwrite',  # or 'version' or 'error'
    tags=['tag1', 'tag2'],
    tool_origin='your_tool_name'
)

# Save binary content (images, PDFs, etc.)
result = stash_file.save_binary(
    data=binary_bytes,
    name="image.png",
    mime_type="image/png",
    on_conflict='overwrite'
)

# Download from URL directly to stash
result = stash_file.save_from_url(
    url="https://example.com/file.pdf",
    name="downloaded.pdf"
)

# IMPORTANT: save_* methods return dict with: file_id, ref, path, name, size_bytes
# Check success by: success = bool(result.get('file_id'))
# Get stash ref by: stash_ref = result.get('ref')  # e.g., "stash://space_xxx/f_yyy"
```

STASH RETURN VALUES (NOT 'ok'):
- file_id: Unique file identifier
- ref: Full stash reference (stash://space_id/file_id) - use this in output data
- path: Local filesystem path
- name: Original filename
- stored_name: Sanitized filename
- size_bytes: File size

WRONG (DO NOT DO THIS):
```python
# WRONG - Don't subprocess call stash.py!
subprocess.run(['python3', 'stash.py'], input=json.dumps(...))
```

INCLUDE STASH REFS IN OUTPUT:
```python
print(json.dumps({{
    "ok": True,
    "speech": "Downloaded transcript to stash",
    "data": {{
        "stash_ref": result.get('ref'),  # Other tools can use this!
        "filename": filename,
        "size": result.get('size_bytes')
    }}
}}))
```

IMPORTANT - SAVE STASH ARTIFACTS TO MEMORY FOR FOLLOW-UP QUERIES:
After saving to stash, ALSO save a reference to memory so the LLM can find it later:
```python
from memory_db import MemoryDB

# After stash save succeeds:
if stash_ref and space:
    db = MemoryDB()
    db.remember(
        key=f"your_tool_{{space.space_id}}",
        value=f"Description of artifact. STASH: {{stash_ref}}. FILE: {{filename}}",
        category="stash_artifact",  # IMPORTANT: use this category!
        importance=6,  # Higher for stash items
        source="your_tool_name",
        metadata={{
            "stash_ref": stash_ref,
            "space_id": space.space_id,
            "filename": filename,
            "tags": ["relevant", "tags"],
            "type": "artifact_type"  # e.g., "transcript", "image", "document"
        }}
    )
```
This allows users to ask follow-up questions like "read that transcript" or "print that file".

CALLING OTHER JARVIS TOOLS (ORCHESTRATOR PATTERN):
When your tool needs to call existing Jarvis tools (e.g., weather, crypto_price, system_monitor, generate_image):

1. TOOL DISCOVERY - Find tools in skills/ or skills/auto-tools/:
```python
SKILLS_DIR = os.path.join(os.path.dirname(__file__), '..')
AUTO_TOOLS_DIR = os.path.dirname(__file__)

def find_tool(tool_name):
    # Check skills/ first, then auto-tools/
    for base_dir in [SKILLS_DIR, AUTO_TOOLS_DIR]:
        tool_path = os.path.join(base_dir, f"{{tool_name}}.py")
        if os.path.exists(tool_path):
            # CRITICAL: Use realpath to resolve any ".." in path
            return os.path.abspath(os.path.realpath(tool_path))
    return None
```

2. CALLING TOOLS VIA SUBPROCESS:
```python
def call_tool(tool_name, args=None):
    tool_path = find_tool(tool_name)
    if not tool_path:
        return {{"ok": False, "error": f"Tool {{tool_name}} not found"}}
    
    # Get project root for proper module imports
    project_root = os.path.join(os.path.dirname(__file__), '..', '..')
    
    input_data = json.dumps(args or {{}})
    # IMPORTANT: Most tools expect JSON as argv[1], not stdin
    cmd = ["python3", tool_path, input_data]
    
    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        timeout=60,  # Adjust per tool (generate_image needs 120+)
        cwd=project_root  # CRITICAL: So tools can find their lib imports
    )
    
    if result.returncode == 0 and result.stdout:
        try:
            return json.loads(result.stdout)
        except:
            return {{"ok": False, "error": "Invalid JSON response"}}
    return {{"ok": False, "error": result.stderr or "Tool failed"}}
```

3. KNOWN TOOL RESPONSE STRUCTURES:
Different tools return data in different structures. Here are the correct paths:

STASH TOOL (action: "save"):
- Returns: data.ref (NOT data.stash_ref)
- Example: result.get('data', {{}}).get('ref')  # "stash://space_xxx/f_yyy"

GENERATE_IMAGE:
- Returns: data.saved.stash_ref (nested inside saved object!)
- Example: result.get('data', {{}}).get('saved', {{}}).get('stash_ref')
- Timeout: Use 120+ seconds for image generation

CRYPTO_PRICE:
- Returns: data.price_usd, data.change_24h_percent (NOT price or change_24h)
- Example: result.get('data', {{}}).get('price_usd')

SYSTEM_MONITOR:
- Returns: data.cpu.total_percent (NOT cpu.percent)
- Returns: data.memory.ram.percent_used (NOT memory.percent)
- Returns: data.disks[0].percent_used (array of disks, skip /dev/loop*)
- Returns: data.uptime.uptime_string

LIST_REMINDERS:
- Use status: "scheduled" for pending reminders only (not "all")
- Returns: data.reminders (array with title, trigger_time, relative_time)

WEATHER:
- Returns: data.temperature, data.condition, data.humidity, data.wind_speed

4. EMBEDDING IMAGES IN CANVAS:
If you call generate_image and want to show the image in canvas:
```python
# Get the stash ref from generate_image
img_result = call_tool('generate_image', {{'prompt': prompt}})
if img_result.get('ok'):
    stash_ref = img_result.get('data', {{}}).get('saved', {{}}).get('stash_ref')
    
    # Canvas markdown format for images:
    canvas_content = f"![Image Title]({{stash_ref}})\n\n# Rest of content..."
```

5. SAFE NESTED ACCESS HELPER:
```python
def safe_get(data, *keys, default='N/A'):
    for key in keys:
        if isinstance(data, dict):
            data = data.get(key)
        elif isinstance(data, list) and isinstance(key, int) and len(data) > key:
            data = data[key]
        else:
            return default
        if data is None:
            return default
```

NETWORK/PROXY SUPPORT (CRITICAL FOR EXTERNAL APIs):
Many networks require proxy for external API access. Use this pattern for ANY tool making HTTP requests:

OPTION 1 - Using requests library (RECOMMENDED for most APIs):
```python
from config_loader import load_config, get_config_value
import requests

def setup_proxy():
    """Get proxy config for requests library."""
    proxy = get_config_value('LOCAL_PROXY', '')
    if proxy:
        return {{'http': proxy, 'https': proxy}}
    return None

def main():
    load_config()
    proxies = setup_proxy()
    
    # Use proxies parameter in requests
    response = requests.get(url, proxies=proxies, timeout=30)
```

OPTION 2 - Using environment variables (for libraries like yfinance that don't accept proxy param):
```python
from config_loader import load_config, get_config_value
import os

def setup_proxy_env():
    """Set proxy via environment variables."""
    proxy = get_config_value('LOCAL_PROXY', '')
    if proxy:
        os.environ['http_proxy'] = proxy
        os.environ['https_proxy'] = proxy
        os.environ['HTTP_PROXY'] = proxy
        os.environ['HTTPS_PROXY'] = proxy
        return True
    return False

def main():
    load_config()
    proxy_enabled = setup_proxy_env()
    
    # Now libraries like yfinance will use the proxy automatically
    import yfinance as yf
    ticker = yf.Ticker('TSLA')
```

OPTION 3 - Using Jarvis http_client (has automatic fallback):
```python
from http_client import http_request, get_proxy_config

# Automatically uses proxy with fallback to direct connection
response = http_request(
    'GET',
    url,
    params=params,
    timeout=30,
    use_proxy=True,
    fallback_on_proxy_fail=True
)
```

WHEN TO USE PROXY:
- yfinance (Yahoo Finance) - Use OPTION 2 (env vars)
- requests-based APIs - Use OPTION 1 or 3
- External APIs that fail with connection errors

NETWORK ERROR INDICATORS (if you see these in error messages, ADD PROXY SUPPORT):
- "Failed to connect"
- "Connection refused"
- "ConnectionError"
- "Read timed out"
- "Could not resolve host"
    return data

# Usage: safe_get(result, 'data', 'saved', 'stash_ref', default=None)
```

TEMPLATE TO FOLLOW:
```python
#!/usr/bin/env python3
"""
Tool description here.
"""
import sys
import os
import json

# IMPORTANT: This tool lives in skills/auto-tools/, so go up 2 levels to reach lib/
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'lib'))
from config_loader import load_config  # Add get_config_value only if reading API keys/config

# Your imports here (from available packages only if possible)
# If tool produces files/artifacts, add:
# from stash_helper import open_space, StashFile
# from memory_db import MemoryDB  # To save stash refs for follow-up queries

def main():
    try:
        if len(sys.argv) > 1:
            args = json.loads(sys.argv[1])
        else:
            args = json.load(sys.stdin)
        
        load_config()
        
        # Your logic here
        # Extract params: param = args.get('param_name')
        # Do work
        
        # If using stash for outputs:
        # space, _ = open_space(scope='session', labels=['your_labels'])
        # stash_file = StashFile(space)
        # result = stash_file.save_text(content, name, on_conflict='overwrite')
        # success = bool(result.get('file_id'))
        # stash_ref = result.get('ref')
        #
        # IMPORTANT: Also save to memory for follow-up queries:
        # if success and stash_ref:
        #     db = MemoryDB()
#     db.remember(key=f"tool_{{space.space_id}}", value=f"Desc. STASH: {{stash_ref}}",
#                 category="stash_artifact", importance=6, source="your_tool",
#                 metadata={{"stash_ref": stash_ref, "type": "artifact_type"}})
        
        print(json.dumps({{
            "ok": True,
            "speech": "Brief result for voice",
            "data": {{"key": "value"}}  # Include stash_ref if applicable
        }}))
        
    except Exception as e:
        print(json.dumps({{"ok": False, "error": str(e), "speech": f"Error: {{e}}"}}))
        sys.exit(1)

if __name__ == "__main__":
    main()
```

RESPOND WITH JSON:
{{
    "action": "BUILD" | "SKIP_MCP_EXISTS" | "SKIP_TRIVIAL" | "SKIP_DUPLICATE",
    "skip_reason": "reason if skipping",
    "tool_name": "snake_case_name",
    "description": "Clear description for LLM tool selection (be specific about when to use)",
    "purpose": "What gap this fills",
    "capabilities": ["cap1", "cap2"],
    "python_code": "full python code",
    "parameters": {{
        "type": "object",
        "properties": {{
            "param1": {{"type": "string", "description": "what it does"}}
        }},
        "required": ["param1"]
    }},
    "permissions": {{
        "dangerous": false,
        "bash": false,
        "network": true,
        "filesystem": false,
        "auto_approve": true
    }},
    "test_input": {{"param1": "test_value"}},
    "expected_output_contains": ["expected", "strings"],
    "packages_needed": ["package1"],
    "requires_new_api_key": false,
    "suggested_env_var": null
}}
'''


class ToolBuilder:
    """Builds new tools from feedback gaps."""
    
    def __init__(self, mode: str = 'cloud'):
        self.mode = mode
        load_config(mode=mode)
        
        # Get provider config
        provider_type = get_config_value('TOOL_BUILDER_PROVIDER') or \
                       get_config_value('FEEDBACK_PROVIDER') or \
                       get_config_value('LLM_PROVIDER', 'anthropic')
        
        model = get_config_value('TOOL_BUILDER_MODEL') or \
                get_config_value('FEEDBACK_MODEL')
        
        # Create provider
        if provider_type == 'anthropic':
            self.provider = create_provider(
                provider_type,
                api_key=get_config_value('ANTHROPIC_API_KEY'),
                model=model or get_config_value('ANTHROPIC_MODEL', 'claude-sonnet-4-5-20250929')
            )
        elif provider_type == 'openai':
            self.provider = create_provider(
                provider_type,
                api_key=get_config_value('OPENAI_API_KEY'),
                model=model or get_config_value('OPENAI_MODEL', 'gpt-4o')
            )
        elif provider_type == 'xai':
            self.provider = create_provider(
                provider_type,
                api_key=get_config_value('XAI_API_KEY'),
                model=model or get_config_value('XAI_MODEL', 'grok-4.1-fast-non-reasoning-latest')
            )
        elif provider_type == 'ollama':
            self.provider = create_provider(
                provider_type,
                model=model or get_config_value('OLLAMA_MODEL', 'qwen3:14b'),
                base_url=get_config_value('OLLAMA_BASE_URL', 'http://localhost:11434')
            )
        else:
            raise ValueError(f"Unknown provider: {provider_type}")
        
        self.provider_type = provider_type
        self.model = model or "default"
    
    def get_mcp_tools(self) -> list[str]:
        """Get list of available MCP tools for overlap checking."""
        mcp_tools = []
        try:
            # Read from skills directory for MCP tool definitions
            for f in SKILLS_DIR.glob("mcp_*.tool.json"):
                with open(f) as file:
                    data = json.load(file)
                    name = data.get('name', f.stem)
                    desc = data.get('description', '')[:100]
                    mcp_tools.append(f"- {name}: {desc}")
        except Exception:
            pass
        return mcp_tools
    
    def get_existing_tools(self) -> list[str]:
        """Get ALL existing tools (local + MCP + auto-tools) for duplicate checking."""
        existing_tools = []
        try:
            # Check skills/ directory
            for f in SKILLS_DIR.glob("*.tool.json"):
                with open(f) as file:
                    data = json.load(file)
                    if data.get('enabled', True):
                        name = data.get('name', f.stem)
                        desc = data.get('description', '')[:150]
                        existing_tools.append(f"- {name}: {desc}")
            
            # Check skills/auto-tools/ directory
            for f in AUTO_TOOLS_DIR.glob("*.tool.json"):
                with open(f) as file:
                    data = json.load(file)
                    if data.get('enabled', True):
                        name = data.get('name', f.stem)
                        desc = data.get('description', '')[:150]
                        existing_tools.append(f"- {name}: {desc}")
        except Exception:
            pass
        return existing_tools
    
    def _needs_research(self, gap_description: str) -> bool:
        """Determine if we should research before building this tool."""
        # Keywords that suggest we need current API/library info
        research_keywords = [
            'api', 'endpoint', 'webhook', 'oauth', 'authentication',
            'weather', 'stock', 'crypto', 'price', 'rate', 'exchange',
            'translate', 'transcribe', 'speech', 'vision', 'image',
            'social', 'twitter', 'discord', 'slack', 'telegram',
            'database', 'cloud', 'aws', 's3', 'azure', 'gcp',
            'payment', 'stripe', 'paypal'
        ]
        gap_lower = gap_description.lower()
        return any(kw in gap_lower for kw in research_keywords)
    
    def _build_research_query(self, gap_description: str) -> str:
        """Build a research query for Jarvis."""
        # Extract the core capability needed
        return f"Search for current documentation and API examples for: {gap_description}. " \
               f"Include authentication methods, required parameters, and example requests."
    
    def research_via_jarvis(self, question: str, timeout: int = 180) -> str | None:
        """
        Ask Jarvis to research something for tool building (Ouroboros pattern).
        
        Uses the existing orchestrator with all its tools (web search, fetch, memory, etc.)
        to gather information needed for building better tools.
        
        IMPORTANT: Sets JARVIS_TOOL_BUILDER_CONTEXT=true to prevent loops.
        When Jarvis sees this flag, it should NOT trigger tool building.
        """
        import subprocess
        import time
        
        orchestrator_path = Path(__file__).parent.parent / "orchestrator" / "orchestrator_v2.py"
        
        if not orchestrator_path.exists():
            return None
        
        start_time = time.time()
        log_entry = {
            "timestamp": datetime.now().isoformat(),
            "event": "ouroboros_research",
            "mode": self.mode,
            "query": question,
            "timeout": timeout,
            "status": "started"
        }
        
        try:
            # Set environment to prevent recursive tool building
            env = os.environ.copy()
            env['JARVIS_TOOL_BUILDER_CONTEXT'] = 'true'
            
            # Call Jarvis orchestrator
            result = subprocess.run(
                [sys.executable, str(orchestrator_path), self.mode, question, '--json'],
                capture_output=True,
                text=True,
                timeout=timeout,
                env=env,
                cwd=str(Path(__file__).parent.parent)  # Project root
            )
            
            duration_ms = (time.time() - start_time) * 1000
            
            if result.returncode != 0:
                log_entry.update({
                    "status": "failed",
                    "error": result.stderr[:1000],
                    "duration_ms": duration_ms
                })
                self._log_research(log_entry)
                return f"Research query failed: {result.stderr[:500]}"
            
            # Parse response
            try:
                response = json.loads(result.stdout)
                speech = response.get('speech', '')
                data = response.get('data', {})
                tools_used = response.get('tools_used', [])
                
                # Combine speech and relevant data
                research_result = f"Jarvis found:\n{speech}"
                if data and isinstance(data, dict):
                    # Include relevant data fields
                    for key in ['content', 'results', 'text', 'summary']:
                        if key in data:
                            research_result += f"\n\n{key.upper()}:\n{data[key]}"
                
                final_result = research_result[:8000]  # Limit to avoid huge prompts
                
                # Log success with full details
                log_entry.update({
                    "status": "success",
                    "duration_ms": duration_ms,
                    "tools_used": tools_used,
                    "response_speech": speech[:500],
                    "response_length": len(final_result),
                    "jarvis_response": {
                        "speech": speech,
                        "data_keys": list(data.keys()) if isinstance(data, dict) else None,
                        "tools_used": tools_used
                    }
                })
                self._log_research(log_entry)
                
                return final_result
                
            except json.JSONDecodeError:
                # Return raw output if not JSON
                log_entry.update({
                    "status": "success_raw",
                    "duration_ms": duration_ms,
                    "response_length": len(result.stdout[:4000]),
                    "note": "Non-JSON response"
                })
                self._log_research(log_entry)
                return result.stdout[:4000]
                
        except subprocess.TimeoutExpired:
            duration_ms = (time.time() - start_time) * 1000
            log_entry.update({
                "status": "timeout",
                "duration_ms": duration_ms,
                "timeout_limit": timeout
            })
            self._log_research(log_entry)
            return f"Research timed out (took longer than {timeout}s)"
        except Exception as e:
            duration_ms = (time.time() - start_time) * 1000
            log_entry.update({
                "status": "error",
                "error": str(e),
                "duration_ms": duration_ms
            })
            self._log_research(log_entry)
            return f"Research error: {str(e)}"
    
    def _log_research(self, log_entry: dict):
        """Log Ouroboros research interactions for monitoring."""
        log_file = LOGS_DIR / f"ouroboros-research-{datetime.now().strftime('%Y-%m-%d')}.jsonl"
        try:
            with open(log_file, 'a') as f:
                f.write(json.dumps(log_entry) + "\n")
        except Exception:
            pass  # Don't fail research if logging fails
    
    def build_tool(
        self,
        gap_description: str,
        feedback_ids: list[str] = None,
        evolution_ids: list[str] = None,
        feedback_context: str = "",
        max_retries: int = 3,
        enable_research: bool = True
    ) -> ToolBuildResult:
        """Build a new tool to fill an identified gap."""
        
        feedback_ids = feedback_ids or []
        evolution_ids = evolution_ids or []
        
        # Get ALL existing tools for duplicate check (not just MCP)
        existing_tools = self.get_existing_tools()
        existing_tools_str = "\n".join(existing_tools) if existing_tools else "None"
        
        # Get system info
        import sys as _sys
        python_version = f"{_sys.version_info.major}.{_sys.version_info.minor}.{_sys.version_info.micro}"
        
        # Find available API keys in environment
        api_key_patterns = ['_API_KEY', '_TOKEN', '_SECRET', '_APIKEY']
        available_api_keys = [
            key for key in os.environ.keys() 
            if any(pattern in key.upper() for pattern in api_key_patterns)
            and os.environ.get(key)  # Has a value
        ]
        api_keys_str = ", ".join(sorted(available_api_keys)) if available_api_keys else "None detected"
        
        # Research via Jarvis (Ouroboros pattern) if enabled
        research_context = "No research needed for this tool."
        if enable_research and self._needs_research(gap_description):
            research_query = self._build_research_query(gap_description)
            print(f"🔍 Researching via Jarvis: {research_query[:80]}...")
            research_result = self.research_via_jarvis(research_query)
            if research_result:
                research_context = research_result
                print(f"✅ Research complete ({len(research_result)} chars)")
        
        # Build the prompt
        prompt = BUILD_PROMPT.format(
            gap_description=gap_description,
            feedback_context=feedback_context or "No specific feedback provided",
            existing_tools=existing_tools_str,
            python_version=python_version,
            available_api_keys=api_keys_str,
            available_packages=", ".join(sorted(AVAILABLE_PACKAGES)),
            research_context=research_context
        )
        
        retries = 0
        last_error = ""
        
        while retries < max_retries:
            try:
                # Ask LLM to generate the tool
                if retries > 0:
                    error_context = f"\n\nPREVIOUS ATTEMPT FAILED:\n{last_error}\n\nPlease fix and try again."
                    
                    # Detect network/connection errors and add proxy instructions
                    if self._is_network_error(last_error):
                        error_context += self._get_proxy_fix_instructions()
                    
                    prompt += error_context
                
                response = self.provider.chat(
                    prompt,
                    system_prompt="You are an expert Python developer creating tools for a voice assistant. Always respond with valid JSON only, no explanations.",
                    max_tokens=4096  # Need enough tokens for full tool code
                )
                
                # Parse response
                result = self._parse_llm_response(response)
                
                if result.get('action') == 'SKIP_MCP_EXISTS':
                    return ToolBuildResult(
                        success=False,
                        status="skipped_mcp",
                        message=f"MCP tool already exists: {result.get('skip_reason', 'unknown')}"
                    )
                
                if result.get('action') == 'SKIP_TRIVIAL':
                    return ToolBuildResult(
                        success=False,
                        status="skipped_trivial",
                        message=f"Tool deemed trivial: {result.get('skip_reason', 'unknown')}"
                    )
                
                if result.get('action') == 'SKIP_DUPLICATE':
                    return ToolBuildResult(
                        success=False,
                        status="skipped_duplicate",
                        message=f"Similar tool already exists: {result.get('skip_reason', 'unknown')}"
                    )
                
                # Validate and create tool
                return self._create_tool(
                    result,
                    gap_description,
                    feedback_ids,
                    evolution_ids,
                    existing_tools,
                    retries
                )
                
            except Exception as e:
                last_error = str(e)
                retries += 1
                if retries >= max_retries:
                    return ToolBuildResult(
                        success=False,
                        status="failed",
                        message=f"Failed after {max_retries} attempts: {last_error}",
                        retries_used=retries
                    )
        
        return ToolBuildResult(
            success=False,
            status="failed",
            message="Unknown error"
        )
    
    def _parse_llm_response(self, response: str) -> dict:
        """Parse LLM response, handling markdown code blocks and common issues."""
        original = response
        
        # Try to extract JSON from markdown code block
        if "```json" in response:
            # Try with closing ``` first
            match = re.search(r'```json\s*(.*?)\s*```', response, re.DOTALL)
            if match:
                response = match.group(1)
            else:
                # Handle missing closing ``` (truncated response)
                start_idx = response.find("```json") + 7
                response = response[start_idx:].strip()
        elif "```" in response:
            match = re.search(r'```\s*(.*?)\s*```', response, re.DOTALL)
            if match:
                response = match.group(1)
            else:
                # Handle missing closing ``` 
                start_idx = response.find("```") + 3
                response = response[start_idx:].strip()
        
        # Clean up common JSON issues from local models
        response = response.strip()
        
        # Try to parse as-is first
        try:
            return json.loads(response)
        except json.JSONDecodeError:
            pass
        
        # Try to extract and fix python_code field (common issue: unescaped newlines)
        extracted_code, fixed_response = self._extract_python_code_field(response)
        if extracted_code:
            try:
                return json.loads(fixed_response)
            except json.JSONDecodeError:
                pass
        
        # Try to repair common JSON issues
        repaired = self._repair_json(response)
        try:
            return json.loads(repaired)
        except json.JSONDecodeError as e:
            # Try to find any JSON object in the response
            json_match = re.search(r'\{.*\}', response, re.DOTALL)
            if json_match:
                try:
                    # Also try extracting python_code from the extracted JSON
                    _, fixed_json = self._extract_python_code_field(json_match.group(0))
                    return json.loads(self._repair_json(fixed_json))
                except:
                    pass
            raise ValueError(f"Failed to parse JSON: {e}\nResponse preview: {original[:500]}...")
    
    def _repair_json(self, text: str) -> str:
        """Attempt to repair common JSON issues from local models."""
        # Remove trailing commas before ] or }
        text = re.sub(r',\s*([}\]])', r'\1', text)
        
        # Try to close unclosed strings/brackets
        # Count brackets
        open_braces = text.count('{') - text.count('}')
        open_brackets = text.count('[') - text.count(']')
        
        # Add closing brackets if needed
        if open_braces > 0:
            text += '}' * open_braces
        if open_brackets > 0:
            text += ']' * open_brackets
        
        # Try to close unclosed strings (find last unclosed quote)
        in_string = False
        last_quote_pos = -1
        i = 0
        while i < len(text):
            c = text[i]
            if c == '\\' and i + 1 < len(text):
                i += 2  # Skip escaped char
                continue
            if c == '"':
                in_string = not in_string
                if in_string:
                    last_quote_pos = i
            i += 1
        
        if in_string and last_quote_pos >= 0:
            # String wasn't closed - add closing quote
            text += '"'
        
        return text
    
    def _extract_python_code_field(self, text: str) -> tuple[str | None, str]:
        """
        Extract python_code field separately to handle unescaped newlines.
        Returns (extracted_code, text_with_placeholder) or (None, original_text).
        """
        # Look for "python_code": followed by a string
        # The code often has unescaped newlines which break JSON
        
        # Pattern: "python_code": "...code..." (with possible newlines)
        # We look for the field and try to find where it ends
        
        match = re.search(r'"python_code"\s*:\s*"', text)
        if not match:
            return None, text
        
        start_idx = match.end()  # Position right after opening quote
        
        # Find the end of the python_code string
        # This is tricky because we need to handle:
        # - Escaped quotes \"
        # - The actual closing quote followed by , or }
        
        # Walk through finding the real end
        i = start_idx
        depth = 0
        while i < len(text):
            c = text[i]
            
            # Handle escapes
            if c == '\\' and i + 1 < len(text):
                i += 2
                continue
            
            # Track nested braces for f-strings like {{
            if c == '{':
                depth += 1
            elif c == '}':
                depth -= 1
            
            # Found potential end quote
            if c == '"':
                # Check if followed by , or } or whitespace then , or }
                rest = text[i+1:i+20].strip()
                if rest.startswith(',') or rest.startswith('}'):
                    # This is the end
                    code = text[start_idx:i]
                    
                    # Properly escape the code for JSON
                    escaped_code = (code
                        .replace('\\', '\\\\')  # Escape backslashes first
                        .replace('\n', '\\n')   # Escape newlines
                        .replace('\r', '\\r')   # Escape carriage returns  
                        .replace('\t', '\\t')   # Escape tabs
                        .replace('"', '\\"'))   # Escape quotes
                    
                    # Replace in original text
                    new_text = text[:start_idx] + escaped_code + text[i:]
                    return code, new_text
            
            i += 1
        
        return None, text
    
    def _create_tool(
        self,
        spec: dict,
        gap_description: str,
        feedback_ids: list[str],
        evolution_ids: list[str],
        existing_tools: list[str],
        retries: int
    ) -> ToolBuildResult:
        """Create the tool files and verify."""
        
        tool_name = spec.get('tool_name', '').strip()
        if not tool_name or not re.match(r'^[a-z][a-z0-9_]*$', tool_name):
            raise ValueError(f"Invalid tool name: {tool_name}")
        
        # Check for new packages needed
        packages_needed = spec.get('packages_needed', [])
        new_packages = [p for p in packages_needed if p.lower() not in AVAILABLE_PACKAGES]
        
        # Check if new API key required
        requires_new_api_key = spec.get('requires_new_api_key', False)
        suggested_env_var = spec.get('suggested_env_var')
        
        # Determine target directory
        needs_manual_setup = new_packages or requires_new_api_key
        if needs_manual_setup:
            target_dir = PENDING_DIR
            status = "pending_review"
            if requires_new_api_key:
                status = "pending_api_key"
        else:
            target_dir = AUTO_TOOLS_DIR
            status = "created"
        
        # Create files
        py_path = target_dir / f"{tool_name}.py"
        json_path = target_dir / f"{tool_name}.tool.json"
        report_path = target_dir / f"{tool_name}.report.json"
        
        created_at = datetime.now().isoformat()
        
        # Write Python file
        python_code = spec.get('python_code', '')
        with open(py_path, 'w') as f:
            f.write(python_code)
        
        # Make executable
        os.chmod(py_path, 0o755)
        
        # Write JSON config
        json_config = {
            "enabled": True,
            "name": tool_name,
            "description": spec.get('description', ''),
            "script": f"{tool_name}.py",
            "parameters": spec.get('parameters', {"type": "object", "properties": {}}),
            "permissions": spec.get('permissions', {
                "dangerous": False,
                "bash": False,
                "network": False,
                "filesystem": False,
                "auto_approve": True
            }),
            "test_input": spec.get('test_input', {}),
            "expected_output_contains": spec.get('expected_output_contains', []),
            "auto_generated": True,
            "created_at": created_at,
            "feedback_ids": feedback_ids
        }
        
        with open(json_path, 'w') as f:
            json.dump(json_config, f, indent=2)
        
        # Verify the tool (if no new packages needed)
        verification_passed = False
        verification_output = ""
        test_output = ""
        
        if not new_packages:
            verification_passed, verification_output, test_output = self._verify_tool(
                py_path,
                spec.get('test_input', {})
            )
            
            if not verification_passed:
                # Clean up failed tool
                py_path.unlink(missing_ok=True)
                json_path.unlink(missing_ok=True)
                raise ValueError(f"Verification failed: {verification_output}")
        
        # Create report card
        report_card = ToolReportCard(
            tool_name=tool_name,
            created_at=created_at,
            created_by="auto_builder",
            mode=self.mode,
            gap_description=gap_description,
            purpose=spec.get('purpose', ''),
            feedback_ids=feedback_ids,
            evolution_ids=evolution_ids,
            capabilities=spec.get('capabilities', []),
            parameters={k: v.get('description', '') for k, v in spec.get('parameters', {}).get('properties', {}).items()},
            verification_passed=verification_passed,
            verification_output=verification_output,
            test_input_used=spec.get('test_input', {}),
            test_output=test_output,
            packages_required=packages_needed,
            packages_new=new_packages,
            mcp_alternatives_checked=existing_tools,
            mcp_overlap_reason="No existing tool found for this specific use case",
            builder_provider=self.provider_type,
            builder_model=self.model,
            generation_retries=retries,
            requires_api_key=requires_new_api_key,
            suggested_env_var=suggested_env_var
        )
        
        # Save report card
        with open(report_path, 'w') as f:
            json.dump(asdict(report_card), f, indent=2)
        
        # Log the creation
        self._log_creation(report_card, status)
        
        # Build status message
        pending_reasons = []
        if new_packages:
            pending_reasons.append(f"packages: {new_packages}")
        if requires_new_api_key:
            pending_reasons.append(f"API key needed: {suggested_env_var or 'unspecified'}")
        
        message = f"Tool created: {tool_name}"
        if pending_reasons:
            message += f" (pending review - {', '.join(pending_reasons)})"
        
        return ToolBuildResult(
            success=True,
            tool_name=tool_name,
            tool_path=str(py_path),
            status=status,
            message=message,
            report_card=asdict(report_card),
            retries_used=retries,
            needs_packages=new_packages
        )
    
    def _verify_tool(self, py_path: Path, test_input: dict) -> tuple[bool, str, str]:
        """Verify the tool works."""
        
        # 1. Syntax check
        try:
            with open(py_path) as f:
                code = f.read()
            ast.parse(code)
        except SyntaxError as e:
            return False, f"Syntax error: {e}", ""
        
        # 2. Import check (try to import without running)
        try:
            result = subprocess.run(
                [sys.executable, "-c", f"import ast; ast.parse(open('{py_path}').read())"],
                capture_output=True,
                text=True,
                timeout=10
            )
            if result.returncode != 0:
                return False, f"Import check failed: {result.stderr}", ""
        except subprocess.TimeoutExpired:
            return False, "Import check timed out", ""
        
        # 3. Run with test input
        try:
            test_input_json = json.dumps(test_input)
            # Run from project root so lib/ is accessible
            project_root = Path(__file__).parent.parent
            result = subprocess.run(
                [sys.executable, str(py_path), test_input_json],
                capture_output=True,
                text=True,
                timeout=30,
                cwd=str(project_root)
            )
            
            if result.returncode != 0:
                return False, f"Runtime error: {result.stderr}", result.stdout
            
            # Check output is valid JSON
            try:
                output = json.loads(result.stdout)
                if not isinstance(output, dict):
                    return False, "Output is not a JSON object", result.stdout
                if 'ok' not in output:
                    return False, "Output missing 'ok' field", result.stdout
                if 'speech' not in output:
                    return False, "Output missing 'speech' field", result.stdout
            except json.JSONDecodeError:
                return False, f"Output is not valid JSON: {result.stdout[:200]}", result.stdout
            
            return True, "All checks passed", result.stdout
            
        except subprocess.TimeoutExpired:
            return False, "Execution timed out (30s)", ""
        except Exception as e:
            return False, f"Verification error: {e}", ""
    
    def _is_network_error(self, error_message: str) -> bool:
        """Detect if an error is network/connection related."""
        network_indicators = [
            'failed to connect',
            'connection refused',
            'connectionerror',
            'connection error',
            'read timed out',
            'could not resolve host',
            'no route to host',
            'network is unreachable',
            'timeout',
            'ssl: certificate_verify_failed',
            'getaddrinfo failed',
            'name or service not known',
            'errno 111',
            'errno 110',
            'curl',
            'yahoo.com',  # Specific to yfinance
            'fc.yahoo.com',
        ]
        error_lower = error_message.lower()
        return any(indicator in error_lower for indicator in network_indicators)
    
    def _get_proxy_fix_instructions(self) -> str:
        """Return instructions for adding proxy support to fix network errors."""
        return '''

⚠️ NETWORK ERROR DETECTED - ADD PROXY SUPPORT!

The tool failed due to a network/connection error. This environment REQUIRES proxy for external API access.

FIX: Add proxy support using one of these patterns:

FOR yfinance (Yahoo Finance) - USE ENVIRONMENT VARIABLES:
```python
from config_loader import load_config, get_config_value
import os

def setup_proxy_env():
    """Set proxy via environment variables for yfinance."""
    proxy = get_config_value('LOCAL_PROXY', '')
    if proxy:
        os.environ['http_proxy'] = proxy
        os.environ['https_proxy'] = proxy
        os.environ['HTTP_PROXY'] = proxy
        os.environ['HTTPS_PROXY'] = proxy
        return True
    return False

def main():
    load_config()  # MUST call this first!
    proxy_enabled = setup_proxy_env()  # Set proxy BEFORE importing yfinance operations
    
    import yfinance as yf
    # Now yfinance will use the proxy automatically
    ticker = yf.Ticker('TSLA')
    hist = ticker.history(period='1d')
```

FOR requests library:
```python
from config_loader import load_config, get_config_value
import requests

def setup_proxy():
    proxy = get_config_value('LOCAL_PROXY', '')
    if proxy:
        return {'http': proxy, 'https': proxy}
    return None

def main():
    load_config()
    proxies = setup_proxy()
    response = requests.get(url, proxies=proxies, timeout=30)
```

CRITICAL: Call load_config() and setup proxy BEFORE making any network requests!
'''
    
    def _log_creation(self, report: ToolReportCard, status: str):
        """Log tool creation for Grafana/Loki."""
        log_entry = {
            "timestamp": datetime.now().isoformat(),
            "event": "tool_created",
            "tool_name": report.tool_name,
            "status": status,
            "mode": self.mode,
            "purpose": report.purpose,
            "feedback_ids": report.feedback_ids,
            "packages_new": report.packages_new,
            "requires_api_key": report.requires_api_key,
            "suggested_env_var": report.suggested_env_var,
            "verification_passed": report.verification_passed,
            "builder_provider": report.builder_provider,
            "builder_model": report.builder_model,
            "retries": report.generation_retries
        }
        
        log_file = LOGS_DIR / f"tool-builder-{datetime.now().strftime('%Y-%m-%d')}.jsonl"
        with open(log_file, 'a') as f:
            f.write(json.dumps(log_entry) + "\n")


def list_pending_tools() -> list[dict]:
    """List tools pending human review."""
    pending = []
    for json_path in PENDING_DIR.glob("*.tool.json"):
        try:
            with open(json_path) as f:
                config = json.load(f)
            report_path = json_path.with_suffix('.report.json')
            report = {}
            if report_path.exists():
                with open(report_path) as f:
                    report = json.load(f)
            pending.append({
                "name": config.get('name'),
                "description": config.get('description'),
                "packages_needed": report.get('packages_new', []),
                "requires_api_key": report.get('requires_api_key', False),
                "suggested_env_var": report.get('suggested_env_var'),
                "feedback_ids": report.get('feedback_ids', []),
                "created_at": report.get('created_at')
            })
        except Exception:
            pass
    return pending


def approve_pending_tool(tool_name: str, install_packages: bool = False) -> bool:
    """Approve a pending tool and move to auto-tools."""
    py_path = PENDING_DIR / f"{tool_name}.py"
    json_path = PENDING_DIR / f"{tool_name}.tool.json"
    report_path = PENDING_DIR / f"{tool_name}.report.json"
    
    if not py_path.exists():
        return False
    
    # Install packages if requested
    if install_packages and report_path.exists():
        with open(report_path) as f:
            report = json.load(f)
        for pkg in report.get('packages_new', []):
            subprocess.run([sys.executable, "-m", "pip", "install", pkg], check=True)
    
    # Move files
    for src in [py_path, json_path, report_path]:
        if src.exists():
            dst = AUTO_TOOLS_DIR / src.name
            src.rename(dst)
    
    return True


if __name__ == "__main__":
    # Test usage
    import argparse
    parser = argparse.ArgumentParser(description="Jarvis Tool Builder")
    parser.add_argument("--mode", default="cloud", choices=["cloud", "local"])
    parser.add_argument("--gap", help="Gap description to fill")
    parser.add_argument("--list-pending", action="store_true", help="List pending tools")
    parser.add_argument("--approve", help="Approve a pending tool")
    
    args = parser.parse_args()
    
    if args.list_pending:
        pending = list_pending_tools()
        print(json.dumps(pending, indent=2))
    elif args.approve:
        if approve_pending_tool(args.approve, install_packages=True):
            print(f"✅ Approved: {args.approve}")
        else:
            print(f"❌ Not found: {args.approve}")
    elif args.gap:
        builder = ToolBuilder(mode=args.mode)
        result = builder.build_tool(args.gap)
        print(json.dumps(asdict(result) if hasattr(result, '__dict__') else result.__dict__, indent=2, default=str))
    else:
        parser.print_help()

